#165305259 Document API using swagger
andela/ah-the-jedi-backend pull request #5
Opened 2019-04-23 15:20 UTC by Benkimeric

#### What does this PR do?
- Adds Swagger documentation to the API
#### Description of Task to be completed?
- Document API using swagger
- Add URL for swagger docs

#### How should this be manually tested?
- Clone this repository ```https://github.com/andela/ah-the-jedi-backend.git``` 
- Checkout to the branch ``` ft-document-with-swagger-165305259```
- Cd into the api directory
- Install all requirements with ```pip install -r requirements.txt```
- Make migrations with the command ```python manage.py makemigrations```
- Migrate the database with ```python manage.py migrate```
- Run server using the command ```python manage.py runserver```
- Go to the URL to view the documentation ```<your-localhost>/api/```

#### Any background context you want to provide?
None
#### What are the relevant pivotal tracker stories?
[#165305259](https://www.pivotaltracker.com/story/show/165305259)

#### Screenshot
<img width="1440" alt="Screenshot 2019-04-23 at 17 36 25" src="https://user-images.githubusercontent.com/19903559/56589663-5b4e7100-65ee-11e9-9990-7ee65af76b12.png">

#### Questions:
Any feedback?

2019-04-23 15:49 UTC, AlvinMugambi approved these changes
Great implementation on integrating swagger

2019-04-23 20:26 UTC, ElishaMisoi approved these changes
Good job @Benkimeric 👍🏽

2019-04-23 20:29 UTC, katherine95 approved these changes

2019-04-24 07:47 UTC, rnjane requested changes
Good work @Benkimeric. One thing before we merge, add a link to the swagger documentation to the repo's readme.

2019-04-25 11:10 UTC, rnjane approved these changes

2019-04-25 11:22 UTC, merged